import urllib.parse
from typing import Dict, Any

def generate_whatsapp_link(phone_number: str, message: str) -> str:
    """
    Generate a WhatsApp link that opens WhatsApp with pre-filled message
    This is the simplest approach - no API required
    """
    # Format phone number (remove spaces, add country code if needed)
    formatted_phone = phone_number.replace(" ", "").replace("-", "").replace("(", "").replace(")", "")
    if not formatted_phone.startswith("+"):
        formatted_phone = "+" + formatted_phone
    
    # URL encode the message
    encoded_message = urllib.parse.quote(message)
    
    # Generate WhatsApp URL
    whatsapp_url = f"https://wa.me/{formatted_phone}?text={encoded_message}"
    
    return whatsapp_url

def create_weekly_report_message(student_name: str, report_data: Dict[str, Any]) -> str:
    """Create a formatted message for weekly report"""
    message = f"""
📚 *Weekly Quran Progress Report*

Assalamu Alaikum {student_name},

Here's your weekly progress summary:

📊 *This Week's Progress:*
• New Memorization: {report_data.get('new_memorization', 'N/A')}
• Recent Revision: {report_data.get('recent_revision', 'N/A')}
• Old Revision: {report_data.get('old_revision', 'N/A')}
• Teacher Notes: {report_data.get('teacher_notes', 'N/A')}

📈 *Summary:*
{report_data.get('summary_text', 'No summary available')}

Keep up the excellent work! May Allah bless your efforts in memorizing the Quran. Ameen.

---
*Generated by Quran Progress Tracker*
    """
    
    return message.strip()

def get_whatsapp_share_link(student_phone: str, student_name: str, report_data: Dict[str, Any]) -> str:
    """Get WhatsApp share link for weekly report"""
    message = create_weekly_report_message(student_name, report_data)
    return generate_whatsapp_link(student_phone, message)

# Example usage
if __name__ == "__main__":
    # Example data
    student_phone = "+1234567890"  # Replace with actual phone number
    student_name = "Hafsa"
    report_data = {
        "new_memorization": "Surah Al-Fatiha Ayah 1-7",
        "recent_revision": "Surah Al-Baqarah Ayah 1-10",
        "old_revision": "Surah Al-Ikhlas",
        "teacher_notes": "Good progress this week",
        "summary_text": "Excellent work this week! Keep practicing regularly."
    }
    
    # Generate WhatsApp link
    whatsapp_link = get_whatsapp_share_link(student_phone, student_name, report_data)
    print(f"WhatsApp Link: {whatsapp_link}")
