import requests
import os
from typing import Optional
import json

class WhatsAppSender:
    def __init__(self):
        # WhatsApp Business API credentials
        self.access_token = os.getenv("WHATSAPP_ACCESS_TOKEN")
        self.phone_number_id = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
        self.base_url = f"https://graph.facebook.com/v18.0/{self.phone_number_id}/messages"
        
    def send_message(self, to_phone: str, message: str) -> bool:
        """Send a text message via WhatsApp Business API"""
        if not self.access_token or not self.phone_number_id:
            print("WhatsApp credentials not configured")
            return False
            
        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json"
        }
        
        data = {
            "messaging_product": "whatsapp",
            "to": to_phone,
            "type": "text",
            "text": {"body": message}
        }
        
        try:
            response = requests.post(self.base_url, headers=headers, json=data)
            response.raise_for_status()
            print(f"WhatsApp message sent successfully to {to_phone}")
            return True
        except requests.exceptions.RequestException as e:
            print(f"Failed to send WhatsApp message: {e}")
            return False
    
    def send_document(self, to_phone: str, document_url: str, filename: str, caption: str = "") -> bool:
        """Send a document (PDF report) via WhatsApp Business API"""
        if not self.access_token or not self.phone_number_id:
            print("WhatsApp credentials not configured")
            return False
            
        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json"
        }
        
        data = {
            "messaging_product": "whatsapp",
            "to": to_phone,
            "type": "document",
            "document": {
                "link": document_url,
                "filename": filename,
                "caption": caption
            }
        }
        
        try:
            response = requests.post(self.base_url, headers=headers, json=data)
            response.raise_for_status()
            print(f"WhatsApp document sent successfully to {to_phone}")
            return True
        except requests.exceptions.RequestException as e:
            print(f"Failed to send WhatsApp document: {e}")
            return False

def send_weekly_report_whatsapp(student_phone: str, student_name: str, report_url: str):
    """Send weekly report via WhatsApp"""
    sender = WhatsAppSender()
    
    # Create the message
    message = f"""
📚 *Weekly Quran Progress Report*

Assalamu Alaikum {student_name},

Your weekly progress report is ready! 

📊 *Report Summary:*
• Student: {student_name}
• Report Type: Weekly Progress
• Generated: {os.popen('date').read().strip()}

📄 The detailed PDF report is attached below.

May Allah bless your efforts in memorizing the Quran. Ameen.

---
*Generated by Quran Progress Tracker*
    """
    
    # Send the message
    success = sender.send_message(student_phone, message)
    
    if success and report_url:
        # Send the PDF document
        sender.send_document(
            to_phone=student_phone,
            document_url=report_url,
            filename=f"Weekly_Report_{student_name}.pdf",
            caption="Weekly Progress Report PDF"
        )
    
    return success
